import { Code, Item } from '@/types';

export const ITEM_DATA = {
  sofa: {
    name: '소파',
    code: 'sofa',
    image: '/images/items/interior/sofa.webp',
    price: 300,
    width: 600,
    height: 400,
    position: {
      top: 30,
      left: 20,
      width: 100,
      height: 10,
    },
    hobby: 'INTERIOR',
    z: 0,
  },

  mirror: {
    name: '거울',
    code: 'mirror',
    image: '/images/items/interior/mirror.webp',
    price: 300,
    width: 480,
    height: 480,
    position: {
      top: 20,
      left: -30,
      width: 80,
      height: 10,
    },
    hobby: 'INTERIOR',
    z: 1,
  },
  shelf: {
    name: '선반',
    code: 'shelf',
    image: '/images/items/interior/shelf.webp',
    price: 300,
    width: 240,
    height: 160,
    position: {
      top: 10,
      left: 2,
      width: 40,
      height: 40,
    },
    hobby: 'INTERIOR',
    z: 0,
  },
  frame: {
    name: '액자',
    code: 'frame',
    image: '/images/items/interior/frame.webp',
    price: 300,
    width: 210,
    height: 210,
    position: {
      top: 15,
      left: 55,
      width: 35,
      height: 10,
    },
    hobby: 'INTERIOR',
    z: 0,
  },
  diffuser: {
    name: '디퓨저',
    code: 'diffuser',
    image: '/images/items/interior/diffuser.webp',
    price: 300,
    width: 210,
    height: 210,
    position: {
      top: 52,
      left: 10,
      width: 25,
      height: 10,
    },
    hobby: 'INTERIOR',
    z: 10,
  },
  circulator: {
    name: '써큘레이터',
    code: 'circulator',
    image: '/images/items/interior/circulator.webp',
    price: 400,
    width: 210,
    height: 210,
    position: {
      top: 52,
      left: 65,
      width: 35,
      height: 10,
    },
    hobby: 'INTERIOR',
    z: 10,
  },
} satisfies Record<Code, Item>;
